# Generated by Django 3.2.7 on 2021-09-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='attachment',
            field=models.FileField(default='N/A', upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='software',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
    ]
