# Generated by Django 3.2.7 on 2021-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20210907_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
